// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA37v4I6HVPin63Rx8VM82ank8H7WhjcB8',
    appId: '1:372957724568:web:4d4e6d14d23f2fbc1735ed',
    messagingSenderId: '372957724568',
    projectId: 'loginpage-5fb95',
    authDomain: 'loginpage-5fb95.firebaseapp.com',
    storageBucket: 'loginpage-5fb95.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANi9X38lA-YDPGtqkE09grWLRX2LiMKqM',
    appId: '1:372957724568:android:e0f48b4e8087ce691735ed',
    messagingSenderId: '372957724568',
    projectId: 'loginpage-5fb95',
    storageBucket: 'loginpage-5fb95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkSJpKHS7GNyibDoZa95jVyLX6MPx0R6o',
    appId: '1:372957724568:ios:f96833c6a16422161735ed',
    messagingSenderId: '372957724568',
    projectId: 'loginpage-5fb95',
    storageBucket: 'loginpage-5fb95.appspot.com',
    iosBundleId: 'com.example.flutterPractice1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkSJpKHS7GNyibDoZa95jVyLX6MPx0R6o',
    appId: '1:372957724568:ios:f96833c6a16422161735ed',
    messagingSenderId: '372957724568',
    projectId: 'loginpage-5fb95',
    storageBucket: 'loginpage-5fb95.appspot.com',
    iosBundleId: 'com.example.flutterPractice1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA37v4I6HVPin63Rx8VM82ank8H7WhjcB8',
    appId: '1:372957724568:web:02353f2a51de05191735ed',
    messagingSenderId: '372957724568',
    projectId: 'loginpage-5fb95',
    authDomain: 'loginpage-5fb95.firebaseapp.com',
    storageBucket: 'loginpage-5fb95.appspot.com',
  );
}
